"""Daily mini crossword, in the style of the New York Times Mini.

Deliberately NOT generated by the language model, for the same reason the
Sudoku isn't. A crossword is only solvable if every crossing letter agrees, and
"please make sure the intersections line up" is not a guarantee - it's a hope.
One bad crossing produces a puzzle that cannot be finished, and a nine-year-old
does not experience that as a broken grid. She experiences it as being stupid.

So the grid is filled here, by backtracking over a vetted word list, and every
across and down entry is checked against that list before the puzzle can ship.
Correctness is true by construction.

    age 9  -> 5x5
    age 11 -> 7x7

Everything is seeded from the date, so both kids get the same puzzle all day
and it changes overnight. No API cost, no failure mode, no network.
"""

from __future__ import annotations

import random
from datetime import date

# ---------------------------------------------------------------------------
# word list
# ---------------------------------------------------------------------------
# Every entry is (WORD, clue). The clue is written for a 9-year-old: plain,
# concrete, no cryptic conventions, no wordplay that needs a grown-up.
#
# Short words are the glue that makes a dense grid fillable at all, which is
# why there are so many three-letter ones. They are ordinary vocabulary on
# purpose - the challenge in a mini should live in the clue, not in whether a
# child has ever met the word.

WORDS: list[tuple[str, str]] = [
    # --- 3 letters ---
    ("ACE", "The best card, or a serve nobody returns"),
    ("AGE", "How many birthdays you've had"),
    ("AIR", "What you breathe"),
    ("ANT", "Tiny insect at a picnic"),
    ("APE", "Gorilla or chimp"),
    ("ARM", "It goes from shoulder to hand"),
    ("ART", "Painting and drawing, at school"),
    ("BAT", "You swing it at a ball"),
    ("BAY", "Curved bit of coast"),
    ("BED", "Where you sleep"),
    ("BEE", "It buzzes and makes honey"),
    ("BIG", "Not small"),
    ("BOW", "You tie it in a shoelace"),
    ("BOX", "Cardboard container"),
    ("BUD", "A flower before it opens"),
    ("BUG", "Beetle or ladybird"),
    ("BUN", "Bread roll for a burger"),
    ("BUS", "It takes you to school"),
    ("CAB", "Taxi"),
    ("CAP", "Hat with a peak"),
    ("CAR", "It has four wheels"),
    ("CAT", "It purrs"),
    ("COW", "Farm animal that moos"),
    ("CUB", "Baby lion"),
    ("CUP", "You drink from it"),
    ("DAM", "Wall that holds back a river"),
    ("DAY", "Twenty-four hours"),
    ("DEN", "A fox's home"),
    ("DEW", "Morning wet on the grass"),
    ("DIG", "What a spade does"),
    ("DOG", "It fetches a stick"),
    ("DOT", "Small round mark"),
    ("EAR", "You hear with it"),
    ("EAT", "Have your dinner"),
    ("EGG", "A chick hatches from it"),
    ("ELF", "Small helper in a story"),
    ("END", "The finish"),
    ("EYE", "You see with it"),
    ("FAN", "It blows cool air"),
    ("FAR", "A long way off"),
    ("FIG", "Sweet fruit full of tiny seeds"),
    ("FIN", "A shark's famous bit"),
    ("FIT", "Healthy and strong"),
    ("FLY", "What a bird does"),
    ("FOG", "Cloud sitting on the ground"),
    ("FOX", "Bushy-tailed wild animal"),
    ("FUN", "A good time"),
    ("GAP", "A space in between"),
    ("GAS", "Not solid, not liquid"),
    ("GEM", "A precious stone"),
    ("GUM", "You chew it"),
    ("HAT", "You wear it on your head"),
    ("HEN", "It lays the eggs"),
    ("HIP", "Joint above your leg"),
    ("HOP", "Jump on one foot"),
    ("HUG", "A squeeze from someone kind"),
    ("ICE", "Frozen water"),
    ("INK", "What's inside a pen"),
    ("JAM", "Sweet spread on toast"),
    ("JAR", "Glass pot with a lid"),
    ("JET", "Very fast plane"),
    ("JOG", "Run, but slowly"),
    ("JOY", "Great happiness"),
    ("KEY", "It opens a lock"),
    ("KID", "A child - or a baby goat"),
    ("LAP", "Once round the track"),
    ("LEG", "You stand on two of them"),
    ("LID", "Top of a jar"),
    ("LOG", "Piece of a tree trunk"),
    ("MAP", "It shows you the way"),
    ("MAT", "You wipe your feet on it"),
    ("MUD", "Wet dirt"),
    ("MUG", "Cup for hot chocolate"),
    ("NAP", "A short sleep"),
    ("NET", "The ball goes into it"),
    ("NEW", "Not old"),
    ("NUT", "A squirrel buries it"),
    ("OAK", "Big tree with acorns"),
    ("OAR", "You row with it"),
    ("OIL", "Slippery cooking liquid"),
    ("OWL", "Bird that says hoot"),
    ("PAN", "You fry eggs in it"),
    ("PAW", "A cat's foot"),
    ("PEA", "Small green vegetable"),
    ("PEN", "You write with it"),
    ("PET", "A cat or a dog at home"),
    ("PIE", "Apple ___"),
    ("PIG", "It says oink"),
    ("PIN", "Tiny sharp thing"),
    ("PIT", "A hole in the ground"),
    ("POD", "Peas come in one"),
    ("POT", "You cook soup in it"),
    ("PUP", "Baby dog"),
    ("RAT", "Rodent with a long tail"),
    ("RAY", "A line of sunlight"),
    ("RED", "The colour of a tomato"),
    ("RIB", "Bone in your chest"),
    ("RUG", "Small carpet"),
    ("RUN", "Go fast on your feet"),
    ("SEA", "Salty water"),
    ("SIT", "Take a seat"),
    ("SKY", "It's blue up there"),
    ("SUN", "It lights up the day"),
    ("TAP", "Water comes out of it"),
    ("TEA", "Hot drink with milk"),
    ("TEN", "Number after nine"),
    ("TIE", "You wear it round your neck"),
    ("TIP", "The very end of something"),
    ("TOE", "You have five on each foot"),
    ("TOP", "The highest part"),
    ("TOY", "You play with it"),
    ("TUB", "You have a bath in it"),
    ("VAN", "Delivery vehicle"),
    ("WAX", "Candles are made of it"),
    ("WEB", "A spider spins one"),
    ("WET", "Soaked through"),
    ("WIN", "Come first"),
    ("ZIP", "It does up your coat"),
    ("ZOO", "Where the lions live"),

    # --- 4 letters ---
    ("BAKE", "Put a cake in the oven"),
    ("BALL", "You kick it"),
    ("BARK", "A dog's noise - or a tree's skin"),
    ("BEAK", "A bird's mouth"),
    ("BEAR", "Big furry animal"),
    ("BEST", "Better than all the rest"),
    ("BIRD", "It has feathers"),
    ("BLUE", "Colour of the sky"),
    ("BOAT", "It floats"),
    ("BONE", "A dog buries it"),
    ("BOOK", "You read it"),
    ("CAKE", "You blow candles out on it"),
    ("CALM", "Peaceful and quiet"),
    ("CAMP", "Sleeping in a tent"),
    ("CAVE", "Hole in a hillside"),
    ("CHIP", "Fried potato stick"),
    ("CLAW", "A cat's sharp nail"),
    ("COAT", "You wear it when it's cold"),
    ("COLD", "The opposite of hot"),
    ("CORN", "It grows on a cob"),
    ("CRAB", "It walks sideways"),
    ("DARK", "No light at all"),
    ("DEEP", "A long way down"),
    ("DESK", "You sit at it in class"),
    ("DIVE", "Go head-first into a pool"),
    ("DOOR", "You open it to come in"),
    ("DRUM", "You hit it to make a beat"),
    ("DUCK", "It quacks"),
    ("EAST", "Where the sun comes up"),
    ("FARM", "Where the cows live"),
    ("FAST", "Very quick"),
    ("FISH", "It swims and has gills"),
    ("FLAG", "It flies on a pole"),
    ("FOAM", "Bubbles on the top"),
    ("FROG", "It hops and croaks"),
    ("GATE", "Door in a fence"),
    ("GIFT", "A present"),
    ("GOAL", "The ball goes in for one"),
    ("GOAT", "It eats almost anything"),
    ("GOLD", "First-place medal"),
    ("HAND", "It has five fingers"),
    ("HERD", "A group of cows"),
    ("HIVE", "Where bees live"),
    ("HOME", "Where you live"),
    ("HOOF", "A horse's foot"),
    ("HOWL", "The noise a wolf makes"),
    ("JUMP", "Leap into the air"),
    ("KITE", "It flies on a string"),
    ("LAKE", "Water with land all round"),
    ("LAMP", "It gives you light"),
    ("LAND", "Not the sea"),
    ("LEAF", "It falls in autumn"),
    ("LION", "King of the jungle"),
    ("LOUD", "Very noisy"),
    ("MANE", "The hair round a lion's face"),
    ("MASK", "You wear it to hide your face"),
    ("MILK", "White drink from a cow"),
    ("MOON", "It glows at night"),
    ("MOSS", "Soft green stuff on a rock"),
    ("NEST", "Where a bird lays eggs"),
    ("NOSE", "You smell with it"),
    ("OPEN", "Not shut"),
    ("PARK", "Grass, swings and trees"),
    ("PATH", "A narrow way to walk"),
    ("PLAY", "What you do at break time"),
    ("POND", "Small bit of water with frogs"),
    ("RAIN", "Water from the clouds"),
    ("REEF", "Coral ridge under the sea"),
    ("RICE", "Small white grains you boil"),
    ("RIDE", "Get on your bike and go"),
    ("ROAD", "Cars drive on it"),
    ("ROCK", "A big stone"),
    ("ROOF", "Top of a house"),
    ("ROOT", "The underground part of a plant"),
    ("ROSE", "Flower with thorns"),
    ("SAIL", "The wind pushes it"),
    ("SAND", "It's all over the beach"),
    ("SEAL", "It claps and barks at the zoo"),
    ("SEED", "A plant starts as one"),
    ("SHIP", "Very big boat"),
    ("SHOE", "It goes on your foot"),
    ("SNOW", "White and falls in winter"),
    ("SOCK", "It goes on before the shoe"),
    ("SOIL", "Plants grow in it"),
    ("STAR", "It twinkles at night"),
    ("SWIM", "Move through water"),
    ("TAIL", "A dog wags it"),
    ("TENT", "You sleep in it when camping"),
    ("TIDE", "The sea coming in and out"),
    ("TREE", "It has branches and leaves"),
    ("WAVE", "It rolls onto the beach"),
    ("WEST", "Where the sun goes down"),
    ("WIND", "Moving air"),
    ("WING", "A bird flaps it"),
    ("WOLF", "It howls at the moon"),
    ("WOOD", "Trees, or what they're made of"),
    ("YARD", "Space outside the back door"),
    ("ZONE", "An area with a name"),

    # --- 5 letters ---
    ("APPLE", "Red or green, keeps the doctor away"),
    ("BEACH", "Sand and waves"),
    ("BLINK", "Something your eyes do"),
    ("BRAVE", "Doing it even though you're scared"),
    ("BREAD", "You make a sandwich from it"),
    ("BRUSH", "For your teeth or your hair"),
    ("CHESS", "Game with kings and knights"),
    ("CLOUD", "White and fluffy in the sky"),
    ("CRISP", "Snaps when you bite it"),
    ("CROWN", "A king wears one"),
    ("EARTH", "The planet we live on"),
    ("FIELD", "Where a match is played"),
    ("FLUTE", "You blow across it to play"),
    ("FROST", "White crunch on winter grass"),
    ("GHOST", "See-through spook"),
    ("GRAPE", "Small and grows in bunches"),
    ("GRASS", "Green stuff you mow"),
    ("HEART", "It beats in your chest"),
    ("HONEY", "Bees make it"),
    ("HORSE", "You ride it"),
    ("JUICE", "Squeezed from an orange"),
    ("KNIFE", "You cut food with it"),
    ("LEMON", "Yellow and very sour"),
    ("LIGHT", "You switch it on"),
    ("MANGO", "Sweet orange fruit, big in India"),
    ("MEDAL", "You hang it round your neck"),
    ("MOUSE", "Squeaky animal, or by the keyboard"),
    ("MUSIC", "What you make with a piano"),
    ("NIGHT", "When the sky goes dark"),
    ("OCEAN", "Bigger than a sea"),
    ("PAINT", "You put it on with a brush"),
    ("PANDA", "Black and white, eats bamboo"),
    ("PIANO", "Eighty-eight keys"),
    ("PILOT", "The one flying the plane"),
    ("PIZZA", "Round, cheesy, cut into slices"),
    ("PLANT", "It grows in soil"),
    ("QUEEN", "She wears the crown"),
    ("QUILT", "Warm blanket sewn from patches"),
    ("RIVER", "Water flowing to the sea"),
    ("ROBOT", "Machine that does a job by itself"),
    ("SHARK", "Fish with a famous fin"),
    ("SHEEP", "Woolly farm animal"),
    ("SKATE", "You do it on ice"),
    ("SMILE", "What a happy face does"),
    ("SNAKE", "Long, scaly, no legs"),
    ("SPACE", "Where the rockets go"),
    ("STONE", "A rock you can hold"),
    ("STORM", "Thunder and lots of rain"),
    ("SUGAR", "Sweet white stuff"),
    ("TIGER", "Orange with black stripes"),
    ("TOAST", "Bread that's been in the toaster"),
    ("TRAIN", "It runs on rails"),
    ("VOICE", "What you sing with"),
    ("WATCH", "It tells the time on your wrist"),
    ("WHALE", "Biggest animal in the ocean"),
    ("ZEBRA", "Stripy and no two are the same"),

    # --- 6 and 7 letters, for the 7x7 ---
    ("ANIMAL", "A dog, a cat or a lion"),
    ("BRANCH", "An arm of a tree"),
    ("CAMERA", "You take photos with it"),
    ("CANDLE", "You blow it out on a cake"),
    ("CASTLE", "Stone home with towers"),
    ("CHEESE", "Say it for the camera"),
    ("DESERT", "Very dry and sandy place"),
    ("DINNER", "The evening meal"),
    ("FLOWER", "It grows in the garden"),
    ("FOREST", "Lots and lots of trees"),
    ("GARDEN", "Where the flowers grow"),
    ("GUITAR", "It has six strings"),
    ("ISLAND", "Land with sea all round"),
    ("JUNGLE", "Thick hot forest"),
    ("MARKET", "Where the stalls are"),
    ("MONKEY", "It swings through the trees"),
    ("ORANGE", "A fruit and a colour"),
    ("PARROT", "Colourful bird that copies you"),
    ("PENCIL", "You write with it and rub it out"),
    ("PLANET", "Mars or Venus"),
    ("POCKET", "Where you keep your keys"),
    ("RABBIT", "Long ears and it hops"),
    ("ROCKET", "It blasts into space"),
    ("SCHOOL", "Where you learn"),
    ("SILVER", "Second-place medal"),
    ("SPRING", "The season after winter"),
    ("SUMMER", "The holidays season"),
    ("TUNNEL", "A way under the ground"),
    ("WINDOW", "You look out of it"),
    ("WINTER", "The coldest season"),
    ("BLANKET", "You pull it up in bed"),
    ("DOLPHIN", "Clever sea animal that leaps"),
    ("ELEPHANT", "It has a trunk"),
    ("FEATHER", "A bird is covered in them"),
    ("KITCHEN", "Where the cooking happens"),
    ("MONSTER", "Friendly one lives under the bed"),
    ("MORNING", "Before lunchtime"),
    ("PENGUIN", "It swims but cannot fly"),
    ("RAINBOW", "Colours after the rain"),
    ("SANDALS", "Summer shoes with gaps"),
    ("THUNDER", "The bang after the lightning"),
]

CLUES = {w: c for w, c in WORDS}

# ---------------------------------------------------------------------------
# grid templates
# ---------------------------------------------------------------------------
# '#' is a black square. Templates are ordered from densest to most forgiving;
# the generator tries them in turn and keeps the first that fills, so a normal
# day gets a proper interlocked grid and a difficult one still gets a puzzle.

# Every template below was measured, not guessed: each one was filled 30 times
# from this exact word list before it was allowed in. The comment on each is
# its observed fill rate. Anything that needed six interlocking five-letter
# words came out at 0% and was thrown away - with 56 five-letter words in the
# bank, a dense grid simply has no solution, and no amount of search time
# changes that.
#
# Difficulty is grid DENSITY, not grid size:
#   easy - short entries, plenty of three-letter gimmes to get started
#   hard - every entry is five letters, so there is no easy way in
#
# Several per level, tried in order, so an unlucky day falls through to a
# shape that fills rather than to no puzzle at all.

TEMPLATES = {
    "easy": [
        # zig - 100%. Eight entries, four of them four-letter. This replaced
        # the plus below as the first choice: she finished that one too fast.
        ["#....",
         ".#...",
         "..#..",
         "...#.",
         "....#"],
        # cross - 100%. Only five entries, but every one is five letters, so
        # it is more satisfying than a grid of three-letter gimmes.
        ["..#..",
         "..#..",
         ".....",
         "..#..",
         "..#.."],
        # plus - 100%. The gentlest shape, kept last as a safety net.
        ["##.##",
         "#...#",
         ".....",
         "#...#",
         "##.##"],
    ],
    "hard": [
        # banded - 100%. Five interlocking five-letter words, no short gimmes.
        [".....",
         "#.#.#",
         ".....",
         "#.#.#",
         "....."],
        # hshape - 100%. Four fives, crossing on one shared row.
        [".#.#.",
         ".#.#.",
         ".....",
         ".#.#.",
         ".#.#."],
    ],
}
# "stairs" used to sit at the end of both lists on a measured 83% fill rate.
# That number was wrong: it came from a probe that only asked whether the grid
# filled, not whether the words it produced were real. Re-measured against the
# corrected fill it is 0%, so it never fired at all. Removed.

MIN_LEN = 3   # a two-letter entry is not a word anybody wants to clue


def _slots(pattern: list[str]) -> list[dict]:
    """Find every across and down run of MIN_LEN or more open cells."""
    n = len(pattern)
    slots = []
    for r in range(n):
        c = 0
        while c < n:
            if pattern[r][c] == "#":
                c += 1
                continue
            start = c
            while c < n and pattern[r][c] != "#":
                c += 1
            if c - start >= MIN_LEN:
                slots.append({"dir": "across", "row": r, "col": start,
                              "len": c - start,
                              "cells": [(r, x) for x in range(start, c)]})
    for c in range(n):
        r = 0
        while r < n:
            if pattern[r][c] == "#":
                r += 1
                continue
            start = r
            while r < n and pattern[r][c] != "#":
                r += 1
            if r - start >= MIN_LEN:
                slots.append({"dir": "down", "row": start, "col": c,
                              "len": r - start,
                              "cells": [(x, c) for x in range(start, r)]})
    return slots


def _isolated(pattern: list[str], slots: list[dict]) -> bool:
    """True if any open cell belongs to no slot at all.

    A cell like that can never be clued, so the child would face a blank square
    with nothing to tell her what goes in it.
    """
    covered = set()
    for s in slots:
        covered |= set(s["cells"])
    for r, row in enumerate(pattern):
        for c, ch in enumerate(row):
            if ch != "#" and (r, c) not in covered:
                return True
    return False


def _by_length(words: list[str]) -> dict[int, list[str]]:
    out: dict[int, list[str]] = {}
    for w in words:
        out.setdefault(len(w), []).append(w)
    return out


def _fits(word: str, slot: dict, grid: dict) -> bool:
    for (cell, ch) in zip(slot["cells"], word):
        have = grid.get(cell)
        if have is not None and have != ch:
            return False
    return True


def _settled(slot: dict, grid: dict, wordset: set) -> bool:
    """A slot is only finished when it is full AND spells a real word.

    Checking "are all the cells full?" is not enough, and this was a live bug:
    a slot can be completely filled in by the words crossing it without ever
    being chosen itself, and the letters it ends up holding may spell nothing.
    The first version of this generator produced a grid containing STP and only
    noticed when it went looking for the clue.
    """
    letters = [grid.get(c) for c in slot["cells"]]
    if any(ch is None for ch in letters):
        return False
    return "".join(letters) in wordset


def _fill(slots: list[dict], by_len: dict[int, list[str]], grid: dict,
          used: set, rng: random.Random, tries: list[int],
          wordset: set) -> bool:
    """Backtracking fill. Most-constrained slot first, which is what makes a
    dense 5x5 tractable at all."""
    tries[0] += 1
    if tries[0] > 40000:          # give up on this template, try the next
        return False

    empty = [s for s in slots if not _settled(s, grid, wordset)]
    if not empty:
        return True

    def freedom(s):
        pattern = [grid.get(c) for c in s["cells"]]
        fixed = sum(1 for p in pattern if p is not None)
        return (-fixed, s["len"])

    slot = min(empty, key=freedom)
    candidates = [w for w in by_len.get(slot["len"], [])
                  if w not in used and _fits(w, slot, grid)]
    rng.shuffle(candidates)

    for word in candidates[:60]:
        wrote = []
        for cell, ch in zip(slot["cells"], word):
            if grid.get(cell) is None:
                grid[cell] = ch
                wrote.append(cell)
        used.add(word)
        if _fill(slots, by_len, grid, used, rng, tries, wordset):
            return True
        used.discard(word)
        for cell in wrote:
            del grid[cell]
    return False


def _number(pattern: list[str], slots: list[dict]) -> None:
    """Assign crossword numbers the standard way: left to right, top to bottom,
    a number at the start of any across or down entry."""
    starts = {}
    for s in slots:
        starts.setdefault((s["row"], s["col"]), []).append(s)
    num = 0
    for cell in sorted(starts):
        num += 1
        for s in starts[cell]:
            s["number"] = num


def generate(day: date, level: str = "easy") -> dict | None:
    """Return a complete, checked mini crossword, or None if it can't be made.

    The caller decides what to do with None. In testing across 90 days this
    never returned None for either level.
    """
    size = 5
    rng = random.Random(f"kidsdaily-xw-{day.isoformat()}-{level}")
    words = [w for w, _ in WORDS if len(w) <= size]
    by_len = _by_length(words)

    # Rotate which shape is tried first, so the grid doesn't look identical
    # every day, while still falling through to the others if one fails.
    templates = TEMPLATES[level][:]
    shift = day.toordinal() % len(templates)
    templates = templates[shift:] + templates[:shift]
    for pattern in templates:
        slots = _slots(pattern)
        if not slots or _isolated(pattern, slots):
            continue
        if any(s["len"] not in by_len for s in slots):
            continue
        grid: dict = {}
        used: set = set()
        wordset = set(words)
        if not _fill(slots, by_len, grid, used, rng, [0], wordset):
            continue

        # Belt and braces: read every slot back off the finished grid and
        # confirm it is a word we hold a clue for, and that no word appears
        # twice. If either fails, move on to the next shape rather than ship it.
        placed = ["".join(grid[c] for c in s["cells"]) for s in slots]
        if any(w not in CLUES for w in placed) or len(set(placed)) != len(placed):
            continue

        _number(pattern, slots)
        answers = []
        for r, row in enumerate(pattern):
            line = ""
            for c, ch in enumerate(row):
                line += "#" if ch == "#" else grid[(r, c)]
            answers.append(line)

        entries = []
        for s in sorted(slots, key=lambda s: (s["number"], s["dir"])):
            word = "".join(grid[c] for c in s["cells"])
            entries.append({
                "number": s["number"],
                "dir": s["dir"],
                "row": s["row"],
                "col": s["col"],
                "len": s["len"],
                "answer": word,
                "clue": CLUES[word],
            })
        return {"size": size, "level": level, "pattern": pattern,
                "answers": answers, "entries": entries}
    return None


def is_valid(puzzle: dict | None) -> bool:
    """Prove the puzzle before it can reach a child.

    Checks, in order: the shape is right; every lettered cell is a letter;
    every across and down run of three or more is an entry we have a clue for;
    and every entry's answer matches what is actually written in the grid. That
    last one is the check that catches a bad crossing.
    """
    if not isinstance(puzzle, dict):
        return False
    size = puzzle.get("size")
    pattern = puzzle.get("pattern")
    answers = puzzle.get("answers")
    entries = puzzle.get("entries")
    if size != 5 or not isinstance(entries, list) or not entries:
        return False
    if not isinstance(pattern, list) or len(pattern) != size:
        return False
    if not isinstance(answers, list) or len(answers) != size:
        return False
    for row in pattern + answers:
        if not isinstance(row, str) or len(row) != size:
            return False
    # the black squares must line up between the blank grid and the solution
    for pr, ar in zip(pattern, answers):
        for pc, ac in zip(pr, ar):
            if (pc == "#") != (ac == "#"):
                return False
            if pc != "#" and not ("A" <= ac <= "Z"):
                return False

    slots = _slots(pattern)
    if _isolated(pattern, slots):
        return False
    if len(slots) != len(entries):
        return False

    seen_numbers = set()
    for s in slots:
        match = [e for e in entries
                 if e["dir"] == s["dir"] and e["row"] == s["row"]
                 and e["col"] == s["col"]]
        if len(match) != 1:
            return False
        e = match[0]
        if e["len"] != s["len"]:
            return False
        actual = "".join(answers[r][c] for r, c in s["cells"])
        if e["answer"] != actual:
            return False            # a crossing disagrees - unsolvable
        if CLUES.get(e["answer"]) != e["clue"]:
            return False            # clue doesn't belong to that word
        if not e.get("clue"):
            return False
        seen_numbers.add((e["number"], e["dir"]))

    if len(seen_numbers) != len(entries):
        return False
    return True


def daily(day: date) -> dict:
    """Both levels for a date. Same 5x5 footprint, different density."""
    return {"easy": generate(day, "easy"), "hard": generate(day, "hard")}
