"""Daily Sudoku generator.

Deliberately NOT generated by the language model. A Sudoku is only a real
puzzle if it has exactly one solution, and that is a hard guarantee to make by
asking nicely. This builds the grid algorithmically and proves uniqueness by
counting solutions, so a broken or ambiguous puzzle cannot reach the page.

Two sizes, matched to the existing age toggle:
    age 9  -> 6x6 grid, 2x3 boxes, digits 1-6
    age 11 -> 9x9 grid, 3x3 boxes, digits 1-9  (gently clued, not expert)

Everything is seeded from the date, so both kids get the same puzzle all day
and it changes overnight. No API cost, no failure mode, no network.
"""

from __future__ import annotations

import random
from datetime import date

# size -> (box_rows, box_cols, givens_to_leave)
SPECS = {
    6: {"box_r": 2, "box_c": 3, "givens": 20},
    9: {"box_r": 3, "box_c": 3, "givens": 38},
}


def _peers(n: int, box_r: int, box_c: int) -> list[list[int]]:
    """Precompute, for each cell, the indices that must differ from it."""
    peers = []
    for i in range(n * n):
        r, c = divmod(i, n)
        s = set()
        for k in range(n):
            s.add(r * n + k)
            s.add(k * n + c)
        br, bc = (r // box_r) * box_r, (c // box_c) * box_c
        for dr in range(box_r):
            for dc in range(box_c):
                s.add((br + dr) * n + (bc + dc))
        s.discard(i)
        peers.append(sorted(s))
    return peers


def _solve(grid: list[int], n: int, peers: list[list[int]], limit: int = 2) -> int:
    """Count solutions, stopping at `limit`. limit=2 answers 'is it unique?'."""
    # pick the empty cell with the fewest candidates (keeps this fast enough
    # to run on every build without anyone noticing)
    best_i, best_opts = -1, None
    for i in range(n * n):
        if grid[i]:
            continue
        used = {grid[p] for p in peers[i] if grid[p]}
        opts = [v for v in range(1, n + 1) if v not in used]
        if not opts:
            return 0
        if best_opts is None or len(opts) < len(best_opts):
            best_i, best_opts = i, opts
            if len(opts) == 1:
                break
    if best_i == -1:
        return 1  # no empties left: a complete, valid grid

    count = 0
    for v in best_opts:
        grid[best_i] = v
        count += _solve(grid, n, peers, limit - count)
        grid[best_i] = 0
        if count >= limit:
            break
    return count


def _full_grid(n: int, peers: list[list[int]], rng: random.Random) -> list[int]:
    """Build a complete valid grid by randomised backtracking."""
    grid = [0] * (n * n)

    def fill(pos: int) -> bool:
        if pos == n * n:
            return True
        used = {grid[p] for p in peers[pos] if grid[p]}
        opts = [v for v in range(1, n + 1) if v not in used]
        rng.shuffle(opts)
        for v in opts:
            grid[pos] = v
            if fill(pos + 1):
                return True
            grid[pos] = 0
        return False

    fill(0)
    return grid


def generate(day: date, size: int = 6) -> dict:
    """Return {size, box_r, box_c, puzzle, solution} for a date.

    `puzzle` uses 0 for blanks. Both grids are flat row-major lists.
    """
    spec = SPECS[size]
    box_r, box_c = spec["box_r"], spec["box_c"]
    peers = _peers(size, box_r, box_c)

    # Seed from the date AND the size so the two levels aren't related.
    rng = random.Random(f"kidsdaily-{day.isoformat()}-{size}")

    solution = _full_grid(size, peers, rng)
    puzzle = solution[:]

    # Remove clues one at a time, keeping the solution unique. Symmetric
    # removal (a cell and its mirror) looks more like a "real" newspaper
    # puzzle, which matters more than it sounds for something a kid picks up.
    order = list(range(size * size))
    rng.shuffle(order)
    target_blanks = size * size - spec["givens"]
    blanks = 0

    for i in order:
        if blanks >= target_blanks:
            break
        mirror = size * size - 1 - i
        cells = [i] if i == mirror else [i, mirror]
        if any(puzzle[c] == 0 for c in cells):
            continue
        saved = [puzzle[c] for c in cells]
        for c in cells:
            puzzle[c] = 0
        if _solve(puzzle[:], size, peers, limit=2) == 1:
            blanks += len(cells)
        else:
            for c, v in zip(cells, saved):
                puzzle[c] = v

    return {
        "size": size,
        "box_r": box_r,
        "box_c": box_c,
        "puzzle": puzzle,
        "solution": solution,
        "givens": size * size - blanks,
    }


def daily(day: date) -> dict:
    """Both difficulty levels for one date."""
    return {"easy": generate(day, 6), "hard": generate(day, 9)}


# --------------------------------------------------------------------------
# validation, used by builder.py before anything reaches the page
# --------------------------------------------------------------------------

def is_valid(pz: dict) -> bool:
    """Structurally sound, self-consistent, and exactly one solution."""
    try:
        size = int(pz["size"])
        if size not in SPECS:
            return False
        box_r, box_c = SPECS[size]["box_r"], SPECS[size]["box_c"]
        if pz.get("box_r") != box_r or pz.get("box_c") != box_c:
            return False
        puzzle, solution = pz["puzzle"], pz["solution"]
        if not (isinstance(puzzle, list) and isinstance(solution, list)):
            return False
        if len(puzzle) != size * size or len(solution) != size * size:
            return False
        if any(not isinstance(v, int) or not 0 <= v <= size for v in puzzle):
            return False
        if any(not isinstance(v, int) or not 1 <= v <= size for v in solution):
            return False

        peers = _peers(size, box_r, box_c)
        # the stated solution must itself be legal
        for i in range(size * size):
            if any(solution[i] == solution[p] for p in peers[i]):
                return False
        # every given must agree with the solution
        for i in range(size * size):
            if puzzle[i] and puzzle[i] != solution[i]:
                return False
        # and there must be exactly one way to finish it
        return _solve(puzzle[:], size, peers, limit=2) == 1
    except Exception:  # noqa: BLE001
        return False
