"""Daily Sudoku generator.

Deliberately NOT generated by the language model. A Sudoku is only a real
puzzle if it has exactly one solution, and that is a hard guarantee to make by
asking nicely. This builds the grid algorithmically and proves uniqueness by
counting solutions, so a broken or ambiguous puzzle cannot reach the page.

Two sizes, matched to the existing age toggle:
    age 9  -> 6x6 grid, 2x3 boxes, digits 1-6
    age 11 -> 9x9 grid, 3x3 boxes, digits 1-9  (gently clued, not expert)

Everything is seeded from the date, so both kids get the same puzzle all day
and it changes overnight. No API cost, no failure mode, no network.
"""

from __future__ import annotations

import random
from datetime import date

# Difficulty here is NOT mainly about how many clues you leave. It is about
# which solving techniques the puzzle demands. A 9x9 with 37 clues can still
# require candidate-pair reasoning or trial and error, which is where an
# 11-year-old gets stuck and gives up.
#
# So every puzzle we ship is guaranteed solvable using only the two techniques
# a child can actually see:
#     naked single  - this cell has only one possible digit
#     hidden single - this digit has only one possible home in its row/col/box
# No guessing, no backtracking, ever. Clue count then tunes how much work it is
# WITHIN that guarantee.
#
# size -> (box_rows, box_cols, target clues to leave)
SPECS = {
    # age 9: fewer clues than before (was 20) so there is more to do, but the
    # singles-only guarantee keeps every step findable.
    6: {"box_r": 2, "box_c": 3, "givens": 15},
    # age 11: more clues than before (was 38) AND singles-only, which is the
    # change that actually matters - the old grid could need techniques she had
    # no way to know.
    9: {"box_r": 3, "box_c": 3, "givens": 44},
}


def _peers(n: int, box_r: int, box_c: int) -> list[list[int]]:
    """Precompute, for each cell, the indices that must differ from it."""
    peers = []
    for i in range(n * n):
        r, c = divmod(i, n)
        s = set()
        for k in range(n):
            s.add(r * n + k)
            s.add(k * n + c)
        br, bc = (r // box_r) * box_r, (c // box_c) * box_c
        for dr in range(box_r):
            for dc in range(box_c):
                s.add((br + dr) * n + (bc + dc))
        s.discard(i)
        peers.append(sorted(s))
    return peers


def _units(n: int, box_r: int, box_c: int) -> list[list[int]]:
    """Every row, column and box, as lists of cell indices."""
    units = []
    for r in range(n):
        units.append([r * n + c for c in range(n)])
    for c in range(n):
        units.append([r * n + c for r in range(n)])
    for br in range(0, n, box_r):
        for bc in range(0, n, box_c):
            units.append([(br + dr) * n + (bc + dc)
                          for dr in range(box_r) for dc in range(box_c)])
    return units


def solve_with_singles(
    puzzle: list[int], n: int, peers: list[list[int]], units: list[list[int]]
) -> tuple[bool, int]:
    """Solve using ONLY naked and hidden singles.

    Returns (solved, steps). If this returns False the puzzle needs something
    cleverer than a child should have to invent, and we don't ship it.
    """
    grid = puzzle[:]
    steps = 0
    while True:
        progress = False

        # naked singles: a cell with exactly one candidate left
        for i in range(n * n):
            if grid[i]:
                continue
            used = {grid[p] for p in peers[i] if grid[p]}
            opts = [v for v in range(1, n + 1) if v not in used]
            if len(opts) == 1:
                grid[i] = opts[0]
                steps += 1
                progress = True
            elif not opts:
                return False, steps  # contradiction

        # hidden singles: a digit with exactly one possible home in a unit
        for unit in units:
            for v in range(1, n + 1):
                if any(grid[i] == v for i in unit):
                    continue
                spots = [
                    i for i in unit
                    if not grid[i] and v not in {grid[p] for p in peers[i] if grid[p]}
                ]
                if len(spots) == 1:
                    grid[spots[0]] = v
                    steps += 1
                    progress = True

        if not progress:
            break

    return all(grid), steps


def _solve(grid: list[int], n: int, peers: list[list[int]], limit: int = 2) -> int:
    """Count solutions, stopping at `limit`. limit=2 answers 'is it unique?'."""
    # pick the empty cell with the fewest candidates (keeps this fast enough
    # to run on every build without anyone noticing)
    best_i, best_opts = -1, None
    for i in range(n * n):
        if grid[i]:
            continue
        used = {grid[p] for p in peers[i] if grid[p]}
        opts = [v for v in range(1, n + 1) if v not in used]
        if not opts:
            return 0
        if best_opts is None or len(opts) < len(best_opts):
            best_i, best_opts = i, opts
            if len(opts) == 1:
                break
    if best_i == -1:
        return 1  # no empties left: a complete, valid grid

    count = 0
    for v in best_opts:
        grid[best_i] = v
        count += _solve(grid, n, peers, limit - count)
        grid[best_i] = 0
        if count >= limit:
            break
    return count


def _full_grid(n: int, peers: list[list[int]], rng: random.Random) -> list[int]:
    """Build a complete valid grid by randomised backtracking."""
    grid = [0] * (n * n)

    def fill(pos: int) -> bool:
        if pos == n * n:
            return True
        used = {grid[p] for p in peers[pos] if grid[p]}
        opts = [v for v in range(1, n + 1) if v not in used]
        rng.shuffle(opts)
        for v in opts:
            grid[pos] = v
            if fill(pos + 1):
                return True
            grid[pos] = 0
        return False

    fill(0)
    return grid


def generate(day: date, size: int = 6) -> dict:
    """Return {size, box_r, box_c, puzzle, solution} for a date.

    `puzzle` uses 0 for blanks. Both grids are flat row-major lists.
    """
    spec = SPECS[size]
    box_r, box_c = spec["box_r"], spec["box_c"]
    peers = _peers(size, box_r, box_c)
    units = _units(size, box_r, box_c)

    # Seed from the date AND the size so the two levels aren't related.
    rng = random.Random(f"kidsdaily-{day.isoformat()}-{size}")

    solution = _full_grid(size, peers, rng)
    puzzle = solution[:]

    # Remove clues one at a time, keeping the solution unique. Symmetric
    # removal (a cell and its mirror) looks more like a "real" newspaper
    # puzzle, which matters more than it sounds for something a kid picks up.
    order = list(range(size * size))
    rng.shuffle(order)
    target_blanks = size * size - spec["givens"]
    blanks = 0

    for i in order:
        if blanks >= target_blanks:
            break
        mirror = size * size - 1 - i
        cells = [i] if i == mirror else [i, mirror]
        if any(puzzle[c] == 0 for c in cells):
            continue
        saved = [puzzle[c] for c in cells]
        for c in cells:
            puzzle[c] = 0
        # Keep the removal only if the puzzle is still uniquely solvable AND
        # still solvable by singles alone. Starting from a full grid (trivially
        # singles-solvable) and only ever removing while that holds means the
        # guarantee is true by construction, not by luck.
        unique = _solve(puzzle[:], size, peers, limit=2) == 1
        gentle = solve_with_singles(puzzle, size, peers, units)[0] if unique else False
        if unique and gentle:
            blanks += len(cells)
        else:
            for c, v in zip(cells, saved):
                puzzle[c] = v

    _, steps = solve_with_singles(puzzle, size, peers, units)
    return {
        "size": size,
        "box_r": box_r,
        "box_c": box_c,
        "puzzle": puzzle,
        "solution": solution,
        "givens": size * size - blanks,
        # how many deductions it takes, as a rough "how long will this feel"
        "steps": steps,
        "singles_only": True,
    }


def daily(day: date) -> dict:
    """Both difficulty levels for one date."""
    return {"easy": generate(day, 6), "hard": generate(day, 9)}


# --------------------------------------------------------------------------
# validation, used by builder.py before anything reaches the page
# --------------------------------------------------------------------------

def is_valid(pz: dict) -> bool:
    """Structurally sound, self-consistent, and exactly one solution."""
    try:
        size = int(pz["size"])
        if size not in SPECS:
            return False
        box_r, box_c = SPECS[size]["box_r"], SPECS[size]["box_c"]
        if pz.get("box_r") != box_r or pz.get("box_c") != box_c:
            return False
        puzzle, solution = pz["puzzle"], pz["solution"]
        if not (isinstance(puzzle, list) and isinstance(solution, list)):
            return False
        if len(puzzle) != size * size or len(solution) != size * size:
            return False
        if any(not isinstance(v, int) or not 0 <= v <= size for v in puzzle):
            return False
        if any(not isinstance(v, int) or not 1 <= v <= size for v in solution):
            return False

        peers = _peers(size, box_r, box_c)
        # the stated solution must itself be legal
        for i in range(size * size):
            if any(solution[i] == solution[p] for p in peers[i]):
                return False
        # every given must agree with the solution
        for i in range(size * size):
            if puzzle[i] and puzzle[i] != solution[i]:
                return False
        # exactly one way to finish it...
        if _solve(puzzle[:], size, peers, limit=2) != 1:
            return False
        # ...and it must be reachable without guessing
        units = _units(size, box_r, box_c)
        return solve_with_singles(puzzle, size, peers, units)[0]
    except Exception:  # noqa: BLE001
        return False
